#!/bin/zsh

# anchor the current folder
BUNDLE=`pwd`

for EXT in `ls -l | egrep '^d' | awk '{print $NF;}'`
    do 
        # method for debugging
        #
        # pwd
        # echo "GOING TO" $EXT && cd $EXT && echo "IM IN"
        # pwd
        # cd $EXT && echo $EXT && git pull
        cd $EXT && git remote show origin | grep Fetch
        cd $BUNDLE
    done

